Adds support for building separate armhf artifacts
wpilibsuite/ntcore pull request #177
Opened 2017-01-03 00:43 UTC by ThadHouse

Currently if using a separate compiler prefix, it would get published to
the arm classifier. This modifies so there is now an armhf classifier
that is used if a separate compiler prefix is used.

2017-01-03 17:47 UTC, 333fred requested changes
Not a fan of this method of telling the difference. Just because I'm using a compiler prefix does not mean I'm compiling for hard float.

2017-01-03 17:52 UTC, ThadHouse commented
I was actually just thinking about that too. I think I'd rather change this to specifically allow another property that would set the postfix. A little more work for the dependencies, but not too bad.

2017-01-04 00:37 UTC, ThadHouse commented
@333fred What do you think of the update? It now has a separate property to choose a prefix.

2017-01-04 00:57 UTC, 333fred approved these changes

2017-01-04 03:12 UTC, merged